Backend/urls.py
from django.contrib import admin
from django.urls import include, path

admin.site.site_header = 'ID Verification - Administration'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.webservice.urls')),
    path('api/user/', include('apps.userservice.urls')),
    path('api/file/', include('apps.fileservice.urls')),
    path('api/id/',   include('apps.idservice.urls')),
]

apps/fileservice/urls.py
from django.urls import include, path

from . import apis

urlpatterns = [
	path("upload/",
		include([
			path("start/", apis.FileDirectUploadStart),
			path("finish/", apis.FileDirectUploadFinish),
			path("replace/", apis.FileReplaceUploadStart),
		]),
	),
	path("getlist/", apis.FileGetList),
	path("get/", apis.FileGet),
	path("edit/", apis.FileEdit),
	path("delete/", apis.FileDelete),
]

apps/idservice/urls.py
from django.urls import include, path

from . import apis

urlpatterns = [
	path("id/getimagepath/", apis.IDGetImagePath),
	path("id/upload/", apis.IDImageUpload),
	path("id/update/result/", apis.IDResultUpload),
	path("matching/get/", apis.MatchingGet),
	path("matching/getlist/", apis.MatchingGetList),
	path("matching/delete/", apis.MatchingDelete),
	path("matching/upload/", apis.MatchingImageUpload),
	path("matching/update/result/", apis.MatchingResultUpload),
]

apps/userservice/urls.py
from django.urls import include, path

from . import apis

urlpatterns = [
	path('login/', apis.auth_login),
	path('logout/', apis.auth_logout),
	# path('register/', apis.auth_register),
	path('me/get/', apis.user_me_get),
	path('me/edit/', apis.user_me_edit),
	path('me/password/', apis.user_me_changepassword),
]

apps/webservice/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('health', views.health_check),
	path('upload_test', views.upload_test),
]

apps/fileservice/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

from .connector import s3_object_delete

class FileModelQuerySet(models.query.QuerySet):
	def delete(self):
		for obj in self.all():
			obj.delete()

class File(models.Model):
	id   = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	name = models.CharField(max_length=255)
	type = models.CharField(max_length=255)
	path = models.CharField(max_length=255, unique=True)
	size = models.IntegerField()
	note = models.TextField(blank=True, null=True)
	tag  = models.CharField(max_length=20, blank=True, null=True)
	creator = models.ForeignKey(User, on_delete=models.CASCADE)

	created  = models.DateTimeField(auto_now_add=True)
	updated  = models.DateTimeField(auto_now=True)
	uploaded = models.DateTimeField(blank=True, null=True)

	objects = FileModelQuerySet.as_manager()

	def __str__(self):
		return f'{self.tag} - {self.name}'

	def deleteFile(self):
		s3_object_delete(file_path=self.path)
		if self.type == 'image/jpeg' or self.type == 'image/png':
			s3_object_delete(file_path=f'user_upload_t/{self.path.split("/")[-1]}')

	def delete(self, using=None, keep_parents=False):
		self.deleteFile()
		super().delete()

	def dict(self):
		return {
			'id': self.id,
			'path': self.path,
			'name': self.name,
			'type': self.type,
			'size': self.size,
			'note': self.note,
			'creator': {
				'id': self.creator.id,
				'username':   self.creator.username,
				'first_name': self.creator.first_name,
				'last_name':  self.creator.last_name,
			},
			'created': self.created,
			'updated': self.updated,
			'uploaded': self.uploaded,
		}

apps/idservice/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

from apps.fileservice.models import File
from apps.fileservice.connector import s3_object_delete

SEX = (('M','Male'), ('F','Female'))
COLOR = (('SIL','Aluminum'),
('AUB','Auburn'),
('BAL','Bald'),
('BGE','Beige'),
('BLK','Black'),
('BLD','Blonde'),
('BLU','Blue'),
('DBL','Blue, Dark'),
('LBL','Blue, Light'),
('BRN','Brown'),
('MAR','Burgundy'),
('COM','Chrome'),
('CPR','Copper'),
('CRM','Cream'),
('GLD','Gold'),
('GRY','Gray'),
('GRN','Green'),
('DGR','Green, Dark'),
('LGR','Green, Light'),
('HAZ','Hazel'),
('CRM','Ivory'),
('LAV','Lavender'),
('MAR','Maroon'),
('ONG','Orange'),
('PNK','Pink'),
('PLE','Purple'),
('RED','Red'),
('SIL','Silver'),
('COM','Stainless Steel'),
('TAN','Tan'),
('TRQ','Turquoise'),
('WHI','White'),
('YEL','Yellow'))

class IDModelQuerySet(models.query.QuerySet):
	def delete(self):
		for obj in self.all():
			obj.delete()

class ID(models.Model):
	id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	driver_license  = models.CharField(max_length=20)
	first_name      = models.CharField(max_length=150, blank=True, null=True)
	last_name       = models.CharField(max_length=150, blank=True, null=True)
	address         = models.TextField(blank=True, null=True)
	date_of_birth   = models.DateField(blank=True, null=True)

	sex             = models.CharField(max_length=1, choices=SEX, blank=True, null=True)
	height          = models.FloatField(blank=True, null=True)
	weight          = models.IntegerField(blank=True, null=True)
	eyes            = models.CharField(max_length=3, choices=COLOR, blank=True, null=True)
	hair            = models.CharField(max_length=3, choices=COLOR, blank=True, null=True)
	vehicle_class   = models.CharField(max_length=1, blank=True, null=True)

	issue_date      = models.DateField(blank=True, null=True)
	expiration_date = models.DateField(blank=True, null=True)

	image           = models.ForeignKey(File, on_delete=models.CASCADE, related_name='id_image', blank=True, null=True)

	created  = models.DateTimeField(auto_now_add=True)
	updated  = models.DateTimeField(auto_now=True)

	result_ocr = models.JSONField(blank=True, null=True)

	objects = IDModelQuerySet.as_manager()

	def __str__(self):
		return self.driver_license
	class Meta:
		verbose_name = 'ID'
		verbose_name_plural = 'IDs'

	def delete(self, using=None, keep_parents=False):
		self.image.delete()
		s3_object_delete(file_path=f"user_upload/debug/{self.image.name}")
		super().delete()

	def dict(self):
		return {
			'id': self.id,
			'driver_license': self.driver_license,
			'first_name': self.first_name,
			'last_name':  self.last_name,
			'created': self.created,
			'updated': self.updated,
			'image': self.image.dict(),
		}
	

class Matching(models.Model):
	id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

	# input
	driver_license   = models.CharField(max_length=20)
	image            = models.ForeignKey(File, on_delete=models.CASCADE, related_name='matching_image', blank=True, null=True)
	
	# output
	face_similarity  = models.FloatField(blank=True, null=True)
	result_face      = models.JSONField(blank=True, null=True)
	result_ocr       = models.JSONField(blank=True, null=True)
	result_matching  = models.JSONField(blank=True, null=True)
	is_matched       = models.BooleanField(blank=True, null=True)

	creator          = models.ForeignKey(User, on_delete=models.CASCADE)
	created          = models.DateTimeField(auto_now_add=True)
	resulted         = models.DateTimeField(blank=True, null=True)

	objects = IDModelQuerySet.as_manager()

	def __str__(self):
		return self.driver_license

	def delete(self, using=None, keep_parents=False):
		self.image.delete()
		s3_object_delete(file_path=f"user_upload/debug/{self.image.name}")
		super().delete()

	def dict(self):
		return {
			'id':              self.id,
			'driver_license':  self.driver_license,
			'image':           self.image.dict(),
			'face_similarity': self.face_similarity,
			'result_face':     self.result_face,
			'result_ocr':      self.result_ocr,
			'result_matching': self.result_matching,
			'is_matched':      self.is_matched,
			'created':         self.created,
			'resulted':        self.resulted,
		}

apps/webservice/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse

def health_check(request):
	return HttpResponse(status=200)

def upload_test(request):
	return render(request, 'upload_test.html')

apps/fileservice/templates/file_change_form.html
{% extends "admin/change_form.html" %}
{% load i18n admin_urls %}

{% block field_sets %}
{% if add %}

<fieldset class="module aligned ">
	<div class="form-row field-tag">
		<label class="required" for="tag">1) Tag:</label>
		<input type="text" name="tag" class="vTextField" maxlength="255" required="" id="tag" value="test">
	</div>
	<div class="form-row">
		<label class="required" for="id_driver_license">2) File:</label>
		<input type="file" onchange="onInputChange(this)">
	</div>
</fieldset>

<script>

	const BASE_BACKEND_URL = `${window.location.protocol}//${window.location.hostname}:${window.location.port}`;

	
	function directUploadStart({fileName, fileType, fileSize}){
		return fetch(`${BASE_BACKEND_URL}/api/file/upload/start/`, {
			method: "POST",
			headers: {
				"Content-Type": "application/json",
			},
			body: JSON.stringify({
				name: fileName,
				type: fileType,
				size: fileSize,
				tag: document.getElementById('tag').value,
			}),
		});
	}
	
	function directUploadDo(data, file){
		const formData = new FormData();
	
		for (const key in data?.fields) {
			formData.append(key, data.fields[key]);
		}
		formData.append('file', file);
	
		formData.forEach((value,key)=>console.log(key,value))
	
		return fetch(data.url, {
			method: "POST",
			headers: {
				'Access-Control-Allow-Origin': '*',
			},
			body: formData,
		});
	}
	
	function directUploadFinish(file_id){
		return fetch(`${BASE_BACKEND_URL}/api/file/upload/finish/`, {
			method: "POST",
			headers: {
				"Content-Type": "application/json",
			},
			body: JSON.stringify({
				id: file_id
			}),
		});
	};
	
	const onInputChange = (element) => {
		const file = element.files[0];
		if (file) {
			directUploadStart({
				fileName: file.name,
				fileType: file.type,
				fileSize: file.size
			})
			.then((response) => response.json())
			.then((data) => {
				directUploadDo(data, file)
					.then(() => {
						directUploadFinish(data.file.id);
					})
					.then(() => {
						console.log('File upload completed!');
						window.location.replace(`/admin/fileservice/file/${data.file.id}/change/`)
					})
			})
			.catch((error) => {
				console.log(error);
				console.log('File upload failed!');
			});
		}
	};
	
	
</script>

{% else %}
{% for fieldset in adminform %}
  {% include "admin/includes/fieldset.html" %}
{% endfor %}
{% endif %}
{% endblock %}

{% block after_field_sets %}
{% if not add %}
<fieldset class="module aligned ">
	<div class="form-row">
		<label class="required" for="tag">Preview:</label>
		<img src="https://d245rtkoblgto6.cloudfront.net/{{original.path}}" style="width: 200px;">
	</div>
</fieldset>
{% endif %}
{% endblock %}

{% block submit_buttons_bottom %}
{% if not add %}{{ block.super }}{% endif %}
{% endblock %}

apps/idservice/templates/id_change_form.html
{% extends "admin/change_form.html" %}
{% load i18n admin_urls %}

{% block after_field_sets %}
{% if not add %}
<fieldset class="module aligned ">
	<div class="form-row">
		<label class="required" for="tag">Preview:</label>
		<a href="https://d245rtkoblgto6.cloudfront.net/{{original.image.path}}" target="_blank"><img src="https://d245rtkoblgto6.cloudfront.net/{{original.image.path}}" style="width: 300px;"></a>
	</div>
	<div class="form-row">
		<label class="required" for="tag">OCR (Debug):</label>
		<a href="https://d245rtkoblgto6.cloudfront.net/user_upload/debug/{{original.image.name}}" target="_blank"><img src="https://d245rtkoblgto6.cloudfront.net/user_upload/debug/{{original.image.name}}" style="width: 300px;"></a>
	</div>
</fieldset>

<script>
	if("{{original.driver_license}}".includes("$null")){
		setTimeout(()=>{
			location.reload();
		}, 5000)
	}
</script>
{% endif %}
{% endblock %}

apps/idservice/templates/id_change_list.html
{% extends "admin/change_list.html" %}
{% load i18n admin_urls %}


{% block object-tools-items %}
<li><a href="/admin/idservice/id/add/" class="addlink">Add id manually</a></li>
<li><a href="#" class="addlink" onclick="document.getElementById('id_upload_image').click()">Add id with image</a></li>

<input style="display: none;" id="id_upload_image" type="file" onchange="onInputChange(this)">

<script>

	const BASE_BACKEND_URL = `${window.location.protocol}//${window.location.hostname}:${window.location.port}`;

	
	function directUploadStart({fileName, fileType, fileSize}){
		return fetch(`${BASE_BACKEND_URL}/api/id/id/upload/`, {
			method: "POST",
			headers: {
				"Content-Type": "application/json",
			},
			body: JSON.stringify({
				name: fileName,
				type: fileType,
				size: fileSize,
			}),
		});
	}
	
	function directUploadDo(data, file){
		const formData = new FormData();
	
		for (const key in data?.fields) {
			formData.append(key, data.fields[key]);
		}
		formData.append('file', file);
	
		formData.forEach((value,key)=>console.log(key,value))
	
		return fetch(data.url, {
			method: "POST",
			headers: {
				'Access-Control-Allow-Origin': '*',
			},
			body: formData,
		});
	}
	
	function directUploadFinish(file_id){
		return fetch(`${BASE_BACKEND_URL}/api/file/upload/finish/`, {
			method: "POST",
			headers: {
				"Content-Type": "application/json",
			},
			body: JSON.stringify({
				id: file_id
			}),
		});
	};
	
	const onInputChange = (element) => {
		const file = element.files[0];
		if (file) {
			directUploadStart({
				fileName: file.name,
				fileType: file.type,
				fileSize: file.size
			})
			.then((response) => response.json())
			.then((data) => {
				directUploadDo(data, file)
					.then(() => {
						directUploadFinish(data.file.id);
					})
					.then(() => {
						console.log('File upload completed!');
						window.location.replace(`/admin/idservice/id/${data.id.id}/change/`)
					})
			})
			.catch((error) => {
				console.log(error);
				console.log('File upload failed!');
			});
		}
	};
	
	
</script>
{% endblock %}

apps/idservice/templates/matching_change_form.html
{% extends "admin/change_form.html" %}
{% load i18n admin_urls %}

{% block field_sets %}
{% if add %}

<div id="errornote"></div>
<fieldset class="module aligned ">
	<div class="form-row">
		<label class="required" for="id_driver_license">ID Card Image:</label>
		<input type="file" onchange="onInputChange(this)">
	</div>
</fieldset>

<script>

	const BASE_BACKEND_URL = `${window.location.protocol}//${window.location.hostname}:${window.location.port}`;

	
	function directUploadStart({fileName, fileType, fileSize}){
		return fetch(`${BASE_BACKEND_URL}/api/id/matching/upload/`, {
			method: "POST",
			headers: {
				"Content-Type": "application/json",
			},
			body: JSON.stringify({
				name: fileName,
				type: fileType,
				size: fileSize,
			}),
		});
	}
	
	function directUploadDo(data, file){
		const formData = new FormData();
	
		for (const key in data?.fields) {
			formData.append(key, data.fields[key]);
		}
		formData.append('file', file);
	
		formData.forEach((value,key)=>console.log(key,value))
	
		return fetch(data.url, {
			method: "POST",
			headers: {
				'Access-Control-Allow-Origin': '*',
			},
			body: formData,
		});
	}
	
	function directUploadFinish(file_id){
		return fetch(`${BASE_BACKEND_URL}/api/file/upload/finish/`, {
			method: "POST",
			headers: {
				"Content-Type": "application/json",
			},
			body: JSON.stringify({
				id: file_id
			}),
		});
	};
	
	const onInputChange = (element) => {
		const file = element.files[0];
		if (file) {
			directUploadStart({
				fileName: file.name,
				fileType: file.type,
				fileSize: file.size
			})
			.then((response) => {
				console.log(response);
				if(response.status == 404) return response.text();
				return response.json();
			})
			.then((data) => {
				if(typeof(data) == 'string') document.getElementById('errornote').innerHTML = `<p class="errornote">${data}</p>`;
				else{
					directUploadDo(data, file)
						.then(() => {
							directUploadFinish(data.file.id);
						})
						.then(() => {
							console.log('File upload completed!');
							window.location.replace(`/admin/idservice/matching/${data.matching.id}/change/`)
						})
				}
			})
			.catch((error) => {
				console.log(error);
				console.log('File upload failed!');
			});
		}
	};
	
	
</script>

{% else %}
{% for fieldset in adminform %}
  {% include "admin/includes/fieldset.html" %}
{% endfor %}
{% endif %}
{% endblock %}

{% block after_field_sets %}
{% if not add %}
<fieldset class="module aligned ">
	<div class="form-row">
		<label class="required" for="tag">Preview:</label>
		<a href="https://d245rtkoblgto6.cloudfront.net/{{original.image.path}}" target="_blank"><img src="https://d245rtkoblgto6.cloudfront.net/{{original.image.path}}" style="width: 300px;"></a>
	</div>
	<div class="form-row">
		<label class="required" for="tag">OCR (Debug):</label>
		<a href="https://d245rtkoblgto6.cloudfront.net/user_upload/debug/{{original.image.name}}" target="_blank"><img src="https://d245rtkoblgto6.cloudfront.net/user_upload/debug/{{original.image.name}}" style="width: 300px;"></a>
	</div>
</fieldset>
{% endif %}
{% endblock %}

{% block submit_buttons_bottom %}
{% if not add %}{{ block.super }}{% endif %}
{% endblock %}

apps/webservice/templates/upload_test.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Saharat CloudDrive</title>

	<script src="https://cdn.jsdelivr.net/npm/d3@7"></script>
</head>
<body>
	<input type="file" id="myfile">
	<div id="message"></div>
</body>
<script>

const BASE_BACKEND_URL = 'http://localhost:8000';

d3.select('#myfile').on('change',(event)=>{
	onInputChange(event);
})

function directUploadStart({fileName, fileType}){
	return fetch(`${BASE_BACKEND_URL}/api/file/upload/start/`, {
		method: "POST",
		headers: {
			"Content-Type": "application/json",
		},
		body: JSON.stringify({
			file_name: fileName,
			file_type: fileType
		}),
	});
}

function directUploadDo(data, file){
	const formData = new FormData();

	for (const key in data?.fields) {
		formData.append(key, data.fields[key]);
	}
	formData.append('file', file);

	formData.forEach((value,key)=>console.log(key,value))

	return fetch(data.url, {
		method: "POST",
		headers: {
			'Access-Control-Allow-Origin': '*',
		},
		body: formData,
	});
}

function directUploadFinish(file_id){
	return fetch(`${BASE_BACKEND_URL}/api/file/upload/finish/`, {
		method: "POST",
		headers: {
			"Content-Type": "application/json",
		},
		body: JSON.stringify({ file_id: file_id}),
	});
};

const onInputChange = (event) => {
	const file = event.target.files[0];
	if (file) {
		directUploadStart({
			fileName: file.name,
			fileType: file.type
		})
		.then((response) => response.json())
		.then((data) => {
			directUploadDo(data, file)
				.then(() => {
					directUploadFinish(data.id);
				})
				.then(() => {
					d3.select('#message').text('File upload completed!');
				})
		})
		.catch((error) => {
			console.log(error);
			d3.select('#message').text('File upload failed!');
		});
	}
};


</script>
</html>